#!/usr/bin/env python3
"""Generate web/catalog.json with 300 AI tools (reference: public AI directory sites)."""
import json
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "catalog.json"
TARGET = 300

PRICING = ("Freemium", "免費", "付費", "試用")

KNOWN_IDS = {
    "ChatGPT": "chatgpt",
    "Claude": "claude",
    "Google Gemini": "gemini",
    "Cursor": "cursor",
    "GitHub Copilot": "github-copilot",
    "Midjourney": "midjourney",
    "DALL·E": "dalle",
    "Canva AI": "canva-ai",
    "Runway": "runway",
    "ElevenLabs": "elevenlabs",
    "Suno": "suno",
    "Perplexity": "perplexity",
    "Notion AI": "notion-ai",
    "DeepL": "deepl",
    "Grammarly": "grammarly",
    "Figma AI": "figma-ai",
    "Stable Diffusion": "stable-diffusion",
    "Kimi": "kimi",
    "Codeium": "codeium",
    "Gamma": "gamma",
    "remove.bg": "remove-bg",
    "Otter.ai": "otter",
    "Jasper": "jasper",
    "Pika": "pika",
    "豆包": "doubao",
    "文心一言": "ernie-bot",
    "讯飞星火": "spark-desk",
    "有道翻譯": "youdao-translate",
    "騰訊翻譯君": "tencent-translate",
    "百度翻譯": "baidu-translate",
}

# (name, url, category, description, tags, keywords, pricing, bestFor, rating)
SEEDS = [
    # --- 對話助手 (existing + new) ---
    ("ChatGPT", "https://chat.openai.com", "對話助手", "OpenAI 出品的通用對話 AI，擅長寫作、問答、腦力激盪與日常任務。", ["聊天", "寫作", "問答", "GPT", "OpenAI"], ["chat", "gpt", "openai", "寫文章", "文案", "通用"], "Freemium", "日常問答與文案撰寫", 4.8),
    ("Claude", "https://claude.ai", "對話助手", "Anthropic 開發的 AI 助手，長文理解與程式碼分析表現優異。", ["聊天", "長文", "分析", "Anthropic"], ["claude", "anthropic", "分析", "程式"], "Freemium", "長文件分析與深度推理", 4.7),
    ("Google Gemini", "https://gemini.google.com", "對話助手", "Google 多模態 AI，整合搜尋與 Google 生態。", ["Google", "搜尋", "多模態"], ["gemini", "google", "搜尋", "research"], "Freemium", "結合搜尋的研究與整理", 4.5),
    ("Kimi", "https://kimi.moonshot.cn", "對話助手", "月之暗面 AI 助手，中文理解強，支援超長上下文。", ["中文", "長上下文", "Moonshot"], ["kimi", "月之暗面", "中文", "長文"], "Freemium", "中文長文理解與問答", 4.5),
    ("Microsoft Copilot", "https://copilot.microsoft.com", "對話助手", "微軟 AI 助手，整合 Bing 搜尋與 Office 生態。", ["微軟", "Bing", "Office"], ["copilot", "microsoft", "bing", "微軟"], "Freemium", "Windows 與 Office 使用者", 4.4),
    ("Grok", "https://grok.com", "對話助手", "xAI 出品的 AI 助手，強調即時資訊與幽默風格。", ["xAI", "即時", "X"], ["grok", "xai", "twitter", "即時"], "Freemium", "即時新聞與社群話題", 4.3),
    ("DeepSeek", "https://chat.deepseek.com", "對話助手", "深度求索 AI，程式與推理能力強，中文支援佳。", ["中文", "推理", "程式"], ["deepseek", "深度求索", "推理", "coding"], "Freemium", "程式推理與中文問答", 4.6),
    ("Meta AI", "https://www.meta.ai", "對話助手", "Meta 官方 AI 助手，整合 WhatsApp、Instagram 等平台。", ["Meta", "Facebook", "社群"], ["meta ai", "facebook", "llama"], "Freemium", "Meta 生態使用者", 4.2),
    ("Mistral Le Chat", "https://chat.mistral.ai", "對話助手", "Mistral AI 對話產品，歐洲開源模型代表，多語言佳。", ["Mistral", "歐洲", "開源"], ["mistral", "le chat", "法國"], "Freemium", "多語言對話與研究", 4.4),
    ("Poe", "https://poe.com", "對話助手", "Quora 出品的多模型聊天平台，可切換 GPT、Claude 等。", ["多模型", "Quora", "聚合"], ["poe", "quora", "多模型"], "Freemium", "一次使用多種 AI 模型", 4.3),
    ("Character.AI", "https://character.ai", "對話助手", "角色扮演 AI 聊天，可與虛擬人物對話或自訂角色。", ["角色", "娛樂", "聊天"], ["character ai", "角色", "roleplay"], "Freemium", "角色扮演與創意對話", 4.2),
    ("Pi", "https://pi.ai", "對話助手", "Inflection AI 的個人化 AI 助手，語氣友善、適合日常陪伴。", ["Inflection", "陪伴", "對話"], ["pi", "inflection", "personal"], "Freemium", "輕鬆日常聊天", 4.1),
    ("HuggingChat", "https://huggingface.co/chat", "對話助手", "Hugging Face 免費開源模型聊天介面。", ["開源", "Hugging Face", "免費"], ["huggingchat", "huggingface", "開源"], "免費", "免費試用開源模型", 4.0),
    ("You.com", "https://you.com", "對話助手", "AI 搜尋與聊天結合，可自訂 AI 模式。", ["搜尋", "聊天", "自訂"], ["you.com", "youchat", "搜尋"], "Freemium", "搜尋加對話混合使用", 4.1),
    ("Phind", "https://www.phind.com", "對話助手", "面向開發者的 AI 搜尋問答，程式問題回答精準。", ["開發", "搜尋", "程式"], ["phind", "developer", "coding"], "Freemium", "開發者技術問答", 4.3),
    ("Qwen Chat", "https://chat.qwen.ai", "對話助手", "阿里通義千問對話產品，中文與多模態能力強。", ["阿里", "通義", "中文"], ["qwen", "通義", "tongyi", "阿里"], "Freemium", "中文與企業場景", 4.4),
    ("豆包", "https://www.doubao.com", "對話助手", "字節跳動 AI 助手，中文對話與創作功能豐富。", ["字節", "中文", "創作"], ["doubao", "豆包", "bytedance"], "Freemium", "中文日常與創意寫作", 4.3),
    ("文心一言", "https://yiyan.baidu.com", "對話助手", "百度文心大模型對話產品，中文理解與搜尋整合。", ["百度", "中文", "搜尋"], ["ernie", "文心", "baidu"], "Freemium", "中文搜尋與問答", 4.2),
    ("讯飞星火", "https://xinghuo.xfyun.cn", "對話助手", "科大訊飛星火認知大模型，中文與語音場景強。", ["訊飛", "中文", "語音"], ["spark", "訊飛", "星火"], "Freemium", "中文語音與教育場景", 4.2),
    ("Replika", "https://replika.com", "對話助手", "AI 陪伴聊天機器人，注重情感互動與個人化。", ["陪伴", "情感", "聊天"], ["replika", "companion", "陪伴"], "Freemium", "情感陪伴與日記對話", 4.0),
    ("OpenRouter", "https://openrouter.ai", "對話助手", "聚合多家 LLM API 的路由平台，開發者與進階用戶適用。", ["API", "聚合", "開發"], ["openrouter", "api", "llm"], "Freemium", "多模型 API 統一入口", 4.3),
    ("Venice AI", "https://venice.ai", "對話助手", "注重隱私的去中心化 AI 聊天，無帳號追蹤。", ["隱私", "去中心化", "聊天"], ["venice", "privacy", "private"], "Freemium", "注重隱私的 AI 對話", 4.1),
    ("LM Studio", "https://lmstudio.ai", "對話助手", "本地運行 LLM 的桌面應用，離線對話與模型管理。", ["本地", "離線", "開源"], ["lm studio", "local", "offline"], "免費", "本地離線 AI 對話", 4.2),
    ("Jan", "https://jan.ai", "對話助手", "開源本地 AI 助手，可離線使用多種開源模型。", ["開源", "本地", "離線"], ["jan ai", "local", "opensource"], "免費", "開源本地 AI 助手", 4.1),
    ("ChatPDF", "https://www.chatpdf.com", "對話助手", "上傳 PDF 後與文件 AI 對話，快速摘要與問答。", ["PDF", "文件", "摘要"], ["chatpdf", "pdf", "document"], "Freemium", "PDF 文件問答", 4.3),
    # --- 程式開發 ---
    ("Cursor", "https://cursor.com", "程式開發", "AI 驅動程式編輯器，可讀取、修改程式碼並執行終端指令。", ["IDE", "編程", "Agent"], ["cursor", "coding", "程式", "agent"], "Freemium", "AI 輔助寫程式與除錯", 4.8),
    ("GitHub Copilot", "https://github.com/features/copilot", "程式開發", "微軟 AI 程式助手，編輯器內即時補全程式碼。", ["GitHub", "補全", "IDE"], ["copilot", "github", "coding"], "付費", "編輯器內程式碼自動補全", 4.6),
    ("Codeium", "https://codeium.com", "程式開發", "免費 AI 程式碼助手，支援多種 IDE 補全與聊天。", ["免費", "補全", "Windsurf"], ["codeium", "windsurf", "free"], "免費", "免費程式碼 AI 補全", 4.4),
    ("Tabnine", "https://www.tabnine.com", "程式開發", "企業級 AI 程式碼補全，支援私有部署。", ["企業", "補全", "私有"], ["tabnine", "enterprise", "autocomplete"], "Freemium", "企業程式碼補全", 4.3),
    ("Amazon Q Developer", "https://aws.amazon.com/q/developer", "程式開發", "AWS 出品 AI 開發助手，整合雲端與程式碼生成。", ["AWS", "雲端", "企業"], ["amazon q", "codewhisperer", "aws"], "Freemium", "AWS 雲端開發輔助", 4.2),
    ("Replit Agent", "https://replit.com", "程式開發", "線上 IDE 與 AI Agent，可從描述生成完整應用。", ["IDE", "Agent", "線上"], ["replit", "agent", "ide"], "Freemium", "快速原型與全端開發", 4.4),
    ("Bolt.new", "https://bolt.new", "程式開發", "StackBlitz AI 全端應用生成，文字描述即可建專案。", ["全端", "Agent", "Web"], ["bolt", "stackblitz", "fullstack"], "Freemium", "文字生成 Web 應用", 4.5),
    ("v0 by Vercel", "https://v0.dev", "程式開發", "Vercel AI UI 生成器，描述即可產出 React 介面。", ["UI", "React", "Vercel"], ["v0", "vercel", "ui", "frontend"], "Freemium", "AI 生成前端 UI", 4.5),
    ("Lovable", "https://lovable.dev", "程式開發", "AI 全端應用建構平台，自然語言生成可部署 App。", ["全端", "No-code", "App"], ["lovable", "gpt engineer", "app"], "Freemium", "自然語言建 Web App", 4.4),
    ("Sourcegraph Cody", "https://sourcegraph.com/cody", "程式開發", "程式碼庫 AI 助手，理解整個 repo 並回答問題。", ["Repo", "搜尋", "企業"], ["cody", "sourcegraph", "codebase"], "Freemium", "大型程式碼庫問答", 4.3),
    ("Continue", "https://continue.dev", "程式開發", "開源 IDE 外掛，連接任意 LLM 輔助寫程式。", ["開源", "外掛", "IDE"], ["continue", "vscode", "opensource"], "免費", "自訂 LLM 程式助手", 4.2),
    ("Aider", "https://aider.chat", "程式開發", "終端機 AI pair programming，直接編輯 git 專案檔案。", ["終端", "Git", "Pair"], ["aider", "cli", "terminal"], "Freemium", "終端機 pair programming", 4.3),
    ("CodeRabbit", "https://coderabbit.ai", "程式開發", "AI Pull Request 程式碼審查，自動提出改進建議。", ["Code Review", "PR", "Git"], ["coderabbit", "review", "pr"], "Freemium", "自動 PR 程式碼審查", 4.4),
    ("Mintlify", "https://mintlify.com", "程式開發", "AI 驅動 API 文件生成與維護平台。", ["文件", "API", "Docs"], ["mintlify", "documentation", "api"], "Freemium", "API 文件自動生成", 4.3),
    ("Sweep AI", "https://sweep.dev", "程式開發", "AI 軟體工程師 Agent，從 GitHub Issue 自動修 bug。", ["Agent", "GitHub", "自動化"], ["sweep", "issue", "automation"], "Freemium", "Issue 自動修復", 4.1),
    ("Devin", "https://devin.ai", "程式開發", "Cognition AI 軟體工程 Agent，可自主完成開發任務。", ["Agent", "自主", "工程"], ["devin", "cognition", "agent"], "付費", "自主軟體工程任務", 4.2),
    ("Blackbox AI", "https://www.blackbox.ai", "程式開發", "AI 程式碼生成與搜尋，支援多語言補全。", ["補全", "搜尋", "多語言"], ["blackbox", "code", "search"], "Freemium", "程式碼生成與搜尋", 4.2),
    ("Pieces", "https://pieces.app", "程式開發", "AI 程式碼片段管理與上下文助手。", ["片段", "生產力", "IDE"], ["pieces", "snippets", "productivity"], "Freemium", "程式碼片段 AI 管理", 4.1),
    ("Supermaven", "https://supermaven.com", "程式開發", "高速 AI 程式碼補全，大上下文窗口。", ["補全", "速度", "IDE"], ["supermaven", "autocomplete"], "Freemium", "高速程式碼補全", 4.2),
    ("JetBrains AI", "https://www.jetbrains.com/ai", "程式開發", "JetBrains IDE 內建 AI 助手，整合 IntelliJ 系列。", ["JetBrains", "IDE", "Java"], ["jetbrains", "intellij", "ai assistant"], "Freemium", "JetBrains IDE 使用者", 4.3),
    ("Snyk Code", "https://snyk.io/product/snyk-code", "程式開發", "AI 驅動程式碼安全掃描與漏洞修復建議。", ["安全", "漏洞", "DevSecOps"], ["snyk", "security", "vulnerability"], "Freemium", "程式碼安全掃描", 4.4),
    ("Qodo", "https://www.qodo.ai", "程式開發", "AI 測試生成與程式碼品質平台（原 CodiumAI）。", ["測試", "品質", "Review"], ["qodo", "codium", "test"], "Freemium", "AI 生成單元測試", 4.2),
    ("Warp AI", "https://www.warp.dev", "程式開發", "AI 增強終端機，自然語言轉 shell 指令。", ["終端", "Shell", "CLI"], ["warp", "terminal", "shell"], "Freemium", "AI 終端機指令助手", 4.3),
    ("Fig", "https://fig.io", "程式開發", "終端機自動完成與 AI 指令建議（Amazon 收購）。", ["終端", "Autocomplete", "CLI"], ["fig", "terminal", "aws"], "Freemium", "終端機自動完成", 4.1),
    ("Mutable AI", "https://mutable.ai", "程式開發", "AI 自動完成與重構程式碼，整合 VS Code。", ["重構", "補全", "VS Code"], ["mutable", "refactor", "vscode"], "Freemium", "程式碼重構輔助", 4.0),
    # --- 圖像生成 ---
    ("Midjourney", "https://www.midjourney.com", "圖像生成", "高品質 AI 繪圖，藝術風格強、視覺效果出色。", ["繪圖", "設計", "藝術"], ["midjourney", "mj", "繪圖", "image"], "付費", "高質感藝術風格圖像", 4.7),
    ("DALL·E", "https://openai.com/dall-e", "圖像生成", "OpenAI AI 繪圖，文字描述生成圖片，與 ChatGPT 整合。", ["OpenAI", "繪圖", "ChatGPT"], ["dalle", "dall-e", "openai"], "Freemium", "快速文字轉圖片", 4.4),
    ("Stable Diffusion", "https://stability.ai", "圖像生成", "開源 AI 繪圖模型，可本地部署，高度客製化。", ["開源", "本地", "ComfyUI"], ["stable diffusion", "sd", "開源"], "免費", "可自架的開源繪圖", 4.3),
    ("Adobe Firefly", "https://firefly.adobe.com", "圖像生成", "Adobe 商用安全 AI 繪圖，整合 Creative Cloud。", ["Adobe", "商用", "設計"], ["firefly", "adobe", "commercial"], "Freemium", "商用安全 AI 繪圖", 4.5),
    ("Leonardo AI", "https://leonardo.ai", "圖像生成", "遊戲與概念藝術 AI 繪圖平台，模型豐富。", ["遊戲", "概念藝術", "3D"], ["leonardo", "game art", "concept"], "Freemium", "遊戲與概念藝術", 4.5),
    ("Ideogram", "https://ideogram.ai", "圖像生成", "擅長文字渲染的 AI 繪圖，海報與 Logo 表現佳。", ["文字", "Logo", "海報"], ["ideogram", "text", "typography"], "Freemium", "含文字的視覺設計", 4.5),
    ("Flux", "https://blackforestlabs.ai", "圖像生成", "Black Forest Labs 高品質開源繪圖模型系列。", ["開源", "寫實", "高品質"], ["flux", "black forest", "realistic"], "Freemium", "寫實風格高品質繪圖", 4.6),
    ("Playground AI", "https://playground.com", "圖像生成", "易用 AI 繪圖平台，混合多種模型與風格。", ["易用", "混合", "社群"], ["playground", "image", "free tier"], "Freemium", "入門 AI 繪圖", 4.3),
    ("NightCafe", "https://creator.nightcafe.studio", "圖像生成", "社群 AI 藝術平台，支援多種演算法與挑戰。", ["社群", "藝術", "挑戰"], ["nightcafe", "community", "art"], "Freemium", "社群 AI 藝術創作", 4.2),
    ("Craiyon", "https://www.craiyon.com", "圖像生成", "免費 AI 繪圖（原 DALL-E mini），快速試玩。", ["免費", "快速", "入門"], ["craiyon", "dalle mini", "free"], "免費", "免費快速試玩繪圖", 4.0),
    ("Krea AI", "https://www.krea.ai", "圖像生成", "即時 AI 繪圖與風格轉換，創意工作流工具。", ["即時", "風格", "工作流"], ["krea", "realtime", "style"], "Freemium", "即時創意繪圖", 4.4),
    ("Magnific AI", "https://magnific.ai", "圖像生成", "AI 圖像放大與細節增強，提升解析度與質感。", ["放大", "增強", "Upscale"], ["magnific", "upscale", "enhance"], "付費", "AI 圖像放大增強", 4.5),
    ("Scenario", "https://www.scenario.com", "圖像生成", "遊戲工作室 AI 素材生成，可訓練自訂風格。", ["遊戲", "自訂", "素材"], ["scenario", "game assets", "custom"], "Freemium", "遊戲素材批量生成", 4.3),
    ("Artbreeder", "https://www.artbreeder.com", "圖像生成", "基因混合式 AI 藝術創作，可融合與演化圖像。", ["混合", "演化", "藝術"], ["artbreeder", "blend", "genetic"], "Freemium", "創意圖像混合演化", 4.1),
    ("BlueWillow", "https://www.bluewillow.ai", "圖像生成", "Discord 社群 AI 繪圖，類 Midjourney 體驗。", ["Discord", "社群", "免費"], ["bluewillow", "discord", "free"], "Freemium", "Discord 社群繪圖", 4.0),
    ("Lexica", "https://lexica.art", "圖像生成", "Stable Diffusion 提示詞搜尋與圖庫平台。", ["提示詞", "搜尋", "SD"], ["lexica", "prompt", "search"], "Freemium", "提示詞靈感搜尋", 4.2),
    ("Tensor.art", "https://tensor.art", "圖像生成", "AI 模型分享與線上生成平台，社群模型豐富。", ["模型", "社群", "SD"], ["tensor art", "models", "community"], "Freemium", "社群模型線上生成", 4.2),
    ("SeaArt", "https://www.seaart.ai", "圖像生成", "多模型 AI 繪圖平台，支援 LoRA 與風格訓練。", ["LoRA", "模型", "亞洲"], ["seaart", "lora", "models"], "Freemium", "多模型繪圖與訓練", 4.3),
    ("DreamStudio", "https://dreamstudio.ai", "圖像生成", "Stability AI 官方 SD 線上繪圖介面。", ["Stability", "SD", "官方"], ["dreamstudio", "stability", "sd"], "Freemium", "官方 Stable Diffusion 介面", 4.2),
    ("Wombo Dream", "https://www.wombodream.com", "圖像生成", "手機 App AI 繪圖，一鍵生成藝術風格圖片。", ["手機", "App", "快速"], ["wombo", "dream", "mobile"], "Freemium", "手機快速 AI 繪圖", 4.0),
    ("StarryAI", "https://starryai.com", "圖像生成", "手機 AI 藝術生成 App，多種風格可選。", ["手機", "App", "藝術"], ["starryai", "mobile", "art"], "Freemium", "手機 AI 藝術 App", 4.0),
    ("getimg.ai", "https://getimg.ai", "圖像生成", "多合一 AI 影像工具，生成、編輯、擴圖一次完成。", ["多合一", "編輯", "擴圖"], ["getimg", "inpaint", "outpaint"], "Freemium", "生成加編輯一站式", 4.3),
    ("Recraft", "https://www.recraft.ai", "圖像生成", "向量風格 AI 繪圖，適合品牌與設計系統。", ["向量", "品牌", "設計"], ["recraft", "vector", "brand"], "Freemium", "向量風格品牌素材", 4.4),
    ("PicLumen", "https://www.piclumen.com", "圖像生成", "免費 AI 繪圖平台，多模型選擇。", ["免費", "多模型", "繪圖"], ["piclumen", "free", "image"], "Freemium", "免費多模型繪圖", 4.1),
    ("Bing Image Creator", "https://www.bing.com/images/create", "圖像生成", "微軟 Bing 免費 DALL-E 繪圖，Microsoft 帳號即可用。", ["微軟", "免費", "DALL-E"], ["bing", "image creator", "microsoft"], "免費", "免費微軟 AI 繪圖", 4.3),
    # --- 設計 ---
    ("Canva AI", "https://www.canva.com", "設計", "Canva 內建 AI，一鍵生成海報、簡報、社群貼文。", ["Canva", "海報", "簡報"], ["canva", "設計", "海報", "ppt"], "Freemium", "非設計師快速做視覺素材", 4.5),
    ("Figma AI", "https://www.figma.com", "設計", "Figma 內建 AI 設計助手，快速生成 UI 原型。", ["Figma", "UI", "UX"], ["figma", "ui", "ux", "prototype"], "Freemium", "UI/UX 設計與原型", 4.4),
    ("Uizard", "https://uizard.io", "設計", "AI 將手繪草圖轉為可編輯 UI 設計。", ["UI", "草圖", "原型"], ["uizard", "wireframe", "sketch"], "Freemium", "草圖轉 UI 設計", 4.3),
    ("Galileo AI", "https://www.usegalileo.ai", "設計", "文字描述生成高保真 UI 設計稿。", ["UI", "高保真", "Figma"], ["galileo", "ui design", "figma"], "Freemium", "文字生成 UI 設計", 4.3),
    ("Khroma", "https://www.khroma.co", "設計", "AI 學習你的色彩偏好，生成配色方案。", ["配色", "色彩", "品牌"], ["khroma", "color", "palette"], "免費", "AI 配色方案生成", 4.2),
    ("Looka", "https://looka.com", "設計", "AI Logo 與品牌識別設計平台。", ["Logo", "品牌", "識別"], ["looka", "logo", "branding"], "付費", "AI Logo 與品牌套件", 4.2),
    ("Brandmark", "https://brandmark.io", "設計", "AI 自動生成 Logo 與品牌素材。", ["Logo", "品牌", "自動"], ["brandmark", "logo", "brand"], "付費", "快速 AI Logo 設計", 4.1),
    ("Designs.ai", "https://designs.ai", "設計", "AI 設計套件，含 Logo、影片、語音等。", ["套件", "Logo", "多媒體"], ["designs.ai", "logo", "video"], "Freemium", "一站式 AI 設計套件", 4.1),
    ("Microsoft Designer", "https://designer.microsoft.com", "設計", "微軟 AI 設計工具，文字生成社群與印刷素材。", ["微軟", "社群", "模板"], ["designer", "microsoft", "social"], "Freemium", "微軟 AI 視覺設計", 4.3),
    ("Kittl", "https://www.kittl.com", "設計", "AI 輔助平面設計，模板與字體豐富。", ["平面", "模板", "字體"], ["kittl", "graphic", "templates"], "Freemium", "平面設計與模板", 4.3),
    ("Visme AI", "https://www.visme.co", "設計", "AI 簡報與資訊圖表設計平台。", ["簡報", "資訊圖", "視覺"], ["visme", "infographic", "presentation"], "Freemium", "資訊圖表與簡報", 4.2),
    ("Magician for Figma", "https://magician.design", "設計", "Figma 外掛 AI，生成圖示、文案與圖片。", ["Figma", "外掛", "圖示"], ["magician", "figma plugin", "icons"], "Freemium", "Figma AI 外掛", 4.2),
    ("Relume", "https://www.relume.io", "設計", "AI 網站 sitemap 與 wireframe 生成。", ["網站", "Wireframe", "Sitemap"], ["relume", "website", "wireframe"], "Freemium", "網站結構與線框圖", 4.4),
    ("Framer AI", "https://www.framer.com", "設計", "AI 生成完整網站頁面，可視化編輯發布。", ["網站", "No-code", "Landing"], ["framer", "website", "landing page"], "Freemium", "AI 生成 Landing Page", 4.5),
    ("Durable", "https://durable.co", "設計", "30 秒 AI 生成完整小型企業網站。", ["網站", "小企", "快速"], ["durable", "website builder", "small business"], "Freemium", "快速生成小企業網站", 4.2),
    ("10Web", "https://10web.io", "設計", "AI WordPress 網站建構與優化平台。", ["WordPress", "網站", "SEO"], ["10web", "wordpress", "website"], "Freemium", "AI WordPress 建站", 4.2),
    ("Hostinger AI", "https://www.hostinger.com/ai-website-builder", "設計", "AI 網站建構器，拖曳加 AI 生成內容。", ["網站", "建站", "Hosting"], ["hostinger", "website builder", "ai"], "Freemium", "AI 網站建構", 4.1),
    ("Spline AI", "https://spline.design", "設計", "AI 3D 設計工具，文字生成 3D 場景。", ["3D", "場景", "互動"], ["spline", "3d", "design"], "Freemium", "AI 3D 場景設計", 4.3),
    ("Autodraw", "https://www.autodraw.com", "設計", "Google AI 塗鴉辨識，自動美化手繪草圖。", ["Google", "塗鴉", "免費"], ["autodraw", "google", "sketch"], "免費", "塗鴉自動美化", 4.0),
    ("Picsart AI", "https://picsart.com", "設計", "AI 照片編輯與創意設計 App，濾鏡與模板豐富。", ["照片", "App", "濾鏡"], ["picsart", "photo edit", "mobile"], "Freemium", "手機 AI 創意設計", 4.3),
    ("Adobe Express", "https://www.adobe.com/express", "設計", "Adobe 輕量設計工具，內建 Firefly AI 功能。", ["Adobe", "Firefly", "社群"], ["adobe express", "firefly", "social"], "Freemium", "輕量 Adobe AI 設計", 4.4),
    ("Miro AI", "https://miro.com/ai", "設計", "白板 AI 助手，生成腦力激盪與流程圖。", ["白板", "協作", "流程圖"], ["miro", "whiteboard", "brainstorm"], "Freemium", "協作白板 AI 整理", 4.3),
    ("Whimsical AI", "https://whimsical.com", "設計", "AI 生成流程圖、線框圖與專案文件。", ["流程圖", "線框", "文件"], ["whimsical", "flowchart", "wireframe"], "Freemium", "流程圖與線框 AI", 4.2),
    ("Mockplus DT", "https://dt.mockplus.com", "設計", "AI 原型設計工具，快速生成互動原型。", ["原型", "互動", "UI"], ["mockplus", "prototype", "ui"], "Freemium", "AI 互動原型設計", 4.1),
    # --- 影片 ---
    ("Runway", "https://runwayml.com", "影片", "專業 AI 影片生成與編輯，文字轉影片、去背、特效。", ["影片", "Gen-3", "剪輯"], ["runway", "video", "gen-3"], "Freemium", "AI 影片生成與剪輯", 4.6),
    ("Pika", "https://pika.art", "影片", "易上手 AI 影片生成，文字或圖片生成短影片。", ["短片", "動畫", "社群"], ["pika", "video", "short"], "Freemium", "輕量 AI 短影片", 4.4),
    ("Sora", "https://openai.com/sora", "影片", "OpenAI 文字生成高品質影片模型。", ["OpenAI", "文字轉影片", "高品質"], ["sora", "openai", "text to video"], "Freemium", "高品質文字轉影片", 4.5),
    ("Luma Dream Machine", "https://lumalabs.ai/dream-machine", "影片", "Luma AI 文字與圖片轉影片，物理效果自然。", ["Luma", "3D", "物理"], ["luma", "dream machine", "video"], "Freemium", "自然物理效果影片", 4.5),
    ("Kling AI", "https://klingai.com", "影片", "快手 AI 影片生成，中文場景支援佳。", ["快手", "中文", "長影片"], ["kling", "kuaishou", "video"], "Freemium", "中文 AI 影片生成", 4.4),
    ("Hailuo AI", "https://hailuoai.com", "影片", "MiniMax AI 影片生成，人物動作流暢。", ["MiniMax", "人物", "動作"], ["hailuo", "minimax", "video"], "Freemium", "人物動態影片", 4.3),
    ("HeyGen", "https://www.heygen.com", "影片", "AI 數位人影片，多語言口型同步。", ["數位人", "Avatar", "多語言"], ["heygen", "avatar", "lip sync"], "Freemium", "AI 數位人影片", 4.5),
    ("Synthesia", "https://www.synthesia.io", "影片", "AI 虛擬主播影片，企業培訓與行銷常用。", ["虛擬主播", "培訓", "企業"], ["synthesia", "avatar", "training"], "付費", "企業培訓 AI 影片", 4.4),
    ("D-ID", "https://www.d-id.com", "影片", "照片轉會說話的 AI 影片，Creative Reality。", ["照片", "Talking", "Avatar"], ["d-id", "talking photo", "avatar"], "Freemium", "照片轉 AI 講話影片", 4.3),
    ("Invideo AI", "https://invideo.io", "影片", "文字腳本一鍵生成完整行銷影片。", ["行銷", "腳本", "模板"], ["invideo", "marketing video", "template"], "Freemium", "腳本轉行銷影片", 4.4),
    ("Pictory", "https://pictory.ai", "影片", "文章或腳本自動轉短影片，社群內容常用。", ["文章轉影片", "社群", "Shorts"], ["pictory", "blog to video", "shorts"], "Freemium", "文章轉短影片", 4.3),
    ("Fliki", "https://fliki.ai", "影片", "文字轉影片加 AI 配音，多語言支援。", ["配音", "文字轉影片", "多語言"], ["fliki", "text to video", "voiceover"], "Freemium", "文字轉影片加配音", 4.3),
    ("Descript", "https://www.descript.com", "影片", "AI 影音編輯，文字編輯即可剪片與去雜音。", ["剪輯", "Podcast", "文字編輯"], ["descript", "video edit", "podcast"], "Freemium", "文字驅動影音剪輯", 4.5),
    ("CapCut AI", "https://www.capcut.com", "影片", "字節剪映 AI 功能，自動字幕、特效與剪輯。", ["剪映", "字幕", "短影片"], ["capcut", "剪映", "tiktok"], "Freemium", "短影片 AI 剪輯", 4.5),
    ("Opus Clip", "https://www.opus.pro", "影片", "長影片 AI 自動剪輯成社群短影片。", ["Shorts", "剪輯", "社群"], ["opus clip", "shorts", "repurpose"], "Freemium", "長片自動剪短影片", 4.4),
    ("Veed.io", "https://www.veed.io", "影片", "線上 AI 影片編輯，字幕、翻譯、去背。", ["線上", "字幕", "翻譯"], ["veed", "subtitle", "online edit"], "Freemium", "線上 AI 影片編輯", 4.3),
    ("Kapwing", "https://www.kapwing.com", "影片", "協作 AI 影片編輯，模板與自動字幕。", ["協作", "模板", "字幕"], ["kapwing", "collaboration", "subtitle"], "Freemium", "協作影片編輯", 4.2),
    ("Topaz Video AI", "https://www.topazlabs.com/topaz-video-ai", "影片", "AI 影片畫質增強與幀率提升。", ["增強", "Upscale", "畫質"], ["topaz video", "upscale", "enhance"], "付費", "AI 影片畫質增強", 4.5),
    ("Wondershare Filmora AI", "https://filmora.wondershare.com", "影片", "AI 智慧剪輯、去背與特效，入門友善。", ["剪輯", "入門", "特效"], ["filmora", "wondershare", "edit"], "Freemium", "入門 AI 影片剪輯", 4.2),
    ("Stable Video Diffusion", "https://stability.ai/stable-video", "影片", "Stability AI 開源影片生成模型。", ["開源", "Stability", "SD"], ["stable video", "stability", "open"], "Freemium", "開源影片生成", 4.2),
    ("Kaiber", "https://kaiber.ai", "影片", "AI 音樂影片與藝術風格動畫生成。", ["音樂影片", "藝術", "動畫"], ["kaiber", "music video", "animation"], "Freemium", "藝術風格動畫影片", 4.2),
    ("Genmo", "https://www.genmo.ai", "影片", "AI 影片與 3D 生成，社群創意平台。", ["3D", "社群", "創意"], ["genmo", "3d", "creative"], "Freemium", "創意 AI 影片", 4.1),
    ("Morph Studio", "https://www.morphstudio.com", "影片", "AI 影片編輯與風格轉換工作台。", ["風格", "轉換", "編輯"], ["morph studio", "style transfer", "video"], "Freemium", "影片風格轉換", 4.0),
    ("Colossyan", "https://www.colossyan.com", "影片", "企業 AI 培訓影片，多語言虛擬講師。", ["培訓", "企業", "多語言"], ["colossyan", "training", "corporate"], "Freemium", "企業培訓 AI 影片", 4.2),
    ("Elai.io", "https://elai.io", "影片", "文字轉 AI 講者影片，無需攝影棚。", ["講者", "文字轉影片", "Avatar"], ["elai", "presenter", "avatar"], "Freemium", "文字轉講者影片", 4.2),
    # --- 語音 ---
    ("ElevenLabs", "https://elevenlabs.io", "語音", "頂尖 AI 語音合成，自然人聲配音與多語言朗讀。", ["配音", "TTS", "語音"], ["elevenlabs", "voice", "tts"], "Freemium", "自然語音合成與配音", 4.7),
    ("Otter.ai", "https://otter.ai", "語音", "AI 會議逐字稿，自動轉錄語音並生成摘要。", ["會議", "逐字稿", "轉錄"], ["otter", "meeting", "transcription"], "Freemium", "會議語音轉文字", 4.4),
    ("Speechify", "https://speechify.com", "語音", "AI 文字朗讀，將文章轉自然語音。", ["朗讀", "TTS", "有聲書"], ["speechify", "read aloud", "audiobook"], "Freemium", "文章 AI 朗讀", 4.4),
    ("Murf AI", "https://murf.ai", "語音", "AI 配音平台，多種專業聲線與語言。", ["配音", "旁白", "廣告"], ["murf", "voiceover", "narration"], "Freemium", "專業 AI 配音", 4.4),
    ("Play.ht", "https://play.ht", "語音", "AI 語音生成 API 與平台，支援克隆聲音。", ["API", "克隆", "TTS"], ["playht", "voice clone", "api"], "Freemium", "語音克隆與 API", 4.3),
    ("Resemble AI", "https://www.resemble.ai", "語音", "AI 語音克隆與情感語音合成。", ["克隆", "情感", "企業"], ["resemble", "voice clone", "emotion"], "Freemium", "語音克隆與情感合成", 4.3),
    ("Descript Overdub", "https://www.descript.com", "語音", "AI 語音克隆，文字編輯即可修改錄音內容。", ["克隆", "編輯", "Podcast"], ["descript overdub", "voice clone", "edit"], "Freemium", "文字編輯語音內容", 4.4),
    ("AssemblyAI", "https://www.assemblyai.com", "語音", "語音轉文字 API，支援摘要與情緒分析。", ["API", "STT", "分析"], ["assemblyai", "speech to text", "api"], "Freemium", "語音轉文字 API", 4.4),
    ("Rev AI", "https://www.rev.ai", "語音", "高精度 AI 語音辨識與字幕 API。", ["STT", "字幕", "API"], ["rev ai", "transcription", "caption"], "Freemium", "高精度語音辨識", 4.3),
    ("Whisper", "https://openai.com/research/whisper", "語音", "OpenAI 開源語音辨識模型，多語言支援。", ["開源", "OpenAI", "STT"], ["whisper", "openai", "speech recognition"], "免費", "開源語音辨識", 4.5),
    ("Fireflies.ai", "https://fireflies.ai", "語音", "AI 會議助手，自動錄音、轉錄與行動項目。", ["會議", "Zoom", "摘要"], ["fireflies", "meeting", "notes"], "Freemium", "會議自動記錄", 4.4),
    ("Fathom", "https://fathom.video", "語音", "免費 AI 會議筆記，自動摘要與重點。", ["會議", "免費", "摘要"], ["fathom", "meeting notes", "free"], "免費", "免費 AI 會議筆記", 4.3),
    ("Krisp", "https://krisp.ai", "語音", "AI 降噪，消除背景雜音提升通話品質。", ["降噪", "通話", "會議"], ["krisp", "noise cancellation", "call"], "Freemium", "通話 AI 降噪", 4.4),
    ("Adobe Podcast", "https://podcast.adobe.com", "語音", "AI 音訊增強，一鍵提升 Podcast 音質。", ["Podcast", "增強", "Adobe"], ["adobe podcast", "enhance", "audio"], "Freemium", "Podcast 音質增強", 4.4),
    ("Cleanvoice", "https://cleanvoice.ai", "語音", "AI 自動去除口癖、停頓與雜音。", ["口癖", "剪輯", "Podcast"], ["cleanvoice", "filler words", "podcast"], "Freemium", "自動去除口癖雜音", 4.3),
    ("Listnr", "https://www.listnr.tech", "語音", "AI 文字轉語音與 Podcast 生成平台。", ["Podcast", "TTS", "生成"], ["listnr", "podcast", "text to speech"], "Freemium", "AI Podcast 生成", 4.2),
    ("WellSaid Labs", "https://wellsaidlabs.com", "語音", "企業級 AI 配音，自然度與一致性高。", ["企業", "配音", "一致性"], ["wellsaid", "enterprise", "voiceover"], "付費", "企業級 AI 配音", 4.4),
    ("LOVO AI", "https://lovo.ai", "語音", "AI 語音生成與情感表達，適合影片旁白。", ["旁白", "情感", "影片"], ["lovo", "voiceover", "video"], "Freemium", "影片旁白 AI 語音", 4.3),
    ("Typecast", "https://typecast.ai", "語音", "AI 虛擬演員配音，可控制情感與語調。", ["演員", "情感", "配音"], ["typecast", "virtual actor", "emotion"], "Freemium", "虛擬演員 AI 配音", 4.2),
    ("Sonantic", "https://sonantic.io", "語音", "影視級 AI 語音，被 Spotify 收購。", ["影視", "情感", "高品質"], ["sonantic", "film", "emotional"], "Freemium", "影視級情感語音", 4.3),
    ("Coqui TTS", "https://coqui.ai", "語音", "開源文字轉語音工具包，可本地部署。", ["開源", "本地", "TTS"], ["coqui", "opensource", "tts"], "免費", "開源 TTS 部署", 4.1),
    ("Tactiq", "https://tactiq.io", "語音", "Google Meet 等會議 AI 即時轉錄。", ["Meet", "即時", "轉錄"], ["tactiq", "google meet", "transcript"], "Freemium", "線上會議即時轉錄", 4.2),
    ("Notta", "https://www.notta.ai", "語音", "AI 語音轉文字，支援 104 種語言。", ["多語言", "STT", "摘要"], ["notta", "transcription", "multilingual"], "Freemium", "多語言語音轉文字", 4.3),
    ("Verbit", "https://verbit.ai", "語音", "企業 AI 轉錄與即時字幕，法律與媒體場景。", ["企業", "字幕", "法律"], ["verbit", "caption", "enterprise"], "付費", "企業即時字幕轉錄", 4.2),
    # --- 音樂 ---
    ("Suno", "https://suno.com", "音樂", "AI 音樂生成，輸入描述即可創作完整歌曲含人聲。", ["音樂", "作曲", "人聲"], ["suno", "music", "song"], "Freemium", "快速生成 AI 音樂", 4.5),
    ("Udio", "https://www.udio.com", "音樂", "AI 音樂創作，高品質人聲與編曲。", ["作曲", "人聲", "編曲"], ["udio", "music", "vocals"], "Freemium", "高品質 AI 歌曲", 4.5),
    ("AIVA", "https://www.aiva.ai", "音樂", "AI 古典與電影配樂作曲，可商用授權。", ["配樂", "古典", "商用"], ["aiva", "soundtrack", "classical"], "Freemium", "電影配樂 AI 作曲", 4.3),
    ("Soundraw", "https://soundraw.io", "音樂", "AI 免版稅背景音樂生成，可自訂長度與情緒。", ["BGM", "免版稅", "背景"], ["soundraw", "royalty free", "bgm"], "Freemium", "免版稅 BGM 生成", 4.3),
    ("Boomy", "https://boomy.com", "音樂", "一鍵 AI 生成歌曲並發布到串流平台。", ["歌曲", "發布", "入門"], ["boomy", "create song", "streaming"], "Freemium", "一鍵創作並發布歌曲", 4.1),
    ("Mubert", "https://mubert.com", "音樂", "AI 即時生成免版稅音樂，適合直播與影片。", ["即時", "免版稅", "直播"], ["mubert", "realtime", "royalty free"], "Freemium", "即時 BGM 生成", 4.2),
    ("Beatoven.ai", "https://www.beatoven.ai", "音樂", "AI 依影片情緒自動生成配樂。", ["配樂", "情緒", "影片"], ["beatoven", "soundtrack", "video mood"], "Freemium", "依情緒生成配樂", 4.2),
    ("Loudly", "https://www.loudly.com", "音樂", "AI 音樂創作平台，社群音樂人協作。", ["社群", "創作", "協作"], ["loudly", "community", "music"], "Freemium", "社群 AI 音樂創作", 4.1),
    ("Ecrett Music", "https://ecrettmusic.com", "音樂", "AI 場景式背景音樂生成，適合影片創作者。", ["場景", "BGM", "創作者"], ["ecrett", "scene", "background music"], "Freemium", "場景式 BGM", 4.2),
    ("Amper Music", "https://www.ampermusic.com", "音樂", "AI 音樂作曲（Shutterstock 旗下），商用授權。", ["商用", "Shutterstock", "作曲"], ["amper", "shutterstock", "commercial"], "Freemium", "商用 AI 配樂", 4.1),
    ("Splash Pro", "https://www.splashmusic.com", "音樂", "AI 音樂創作 App，適合入門與教育。", ["App", "入門", "教育"], ["splash", "mobile", "beginner"], "Freemium", "入門 AI 音樂 App", 4.0),
    ("Riffusion", "https://www.riffusion.com", "音樂", "AI 即時音樂生成，視覺化頻譜繪圖。", ["即時", "視覺", "實驗"], ["riffusion", "realtime", "spectrogram"], "Freemium", "實驗性 AI 音樂", 4.0),
    ("Stable Audio", "https://stableaudio.com", "音樂", "Stability AI 文字生成音樂與音效。", ["Stability", "音效", "文字轉音樂"], ["stable audio", "stability", "sound effects"], "Freemium", "文字生成音樂音效", 4.3),
    ("AudioCraft", "https://ai.meta.com/resources/models-and-libraries/audiocraft", "音樂", "Meta 開源音訊生成模型套件 MusicGen。", ["Meta", "開源", "MusicGen"], ["audiocraft", "musicgen", "meta"], "免費", "開源音樂生成", 4.2),
    ("Voicemod AI", "https://www.voicemod.net", "音樂", "AI 變聲與音效，直播與遊戲常用。", ["變聲", "直播", "遊戲"], ["voicemod", "voice changer", "streaming"], "Freemium", "AI 變聲與音效", 4.2),
    ("Endel", "https://endel.io", "音樂", "AI 個人化環境音樂，依時間與心情調整。", ["環境", "專注", "睡眠"], ["endel", "ambient", "focus"], "Freemium", "個人化環境音樂", 4.2),
    ("Brain.fm", "https://www.brain.fm", "音樂", "AI 生成專注與放鬆音樂，科學驗證。", ["專注", "放鬆", "科學"], ["brain.fm", "focus", "productivity"], "Freemium", "專注力 AI 音樂", 4.3),
    ("LALAL.AI", "https://www.lalal.ai", "音樂", "AI 人聲與樂器分離，提取伴奏或人聲。", ["分離", "伴奏", "Remix"], ["lalal", "stem separation", "vocals"], "Freemium", "人聲樂器分離", 4.4),
    ("Moises", "https://moises.ai", "音樂", "AI 音樂練習工具，分離音軌與調整速度。", ["練習", "分軌", "音樂人"], ["moises", "practice", "stems"], "Freemium", "音樂人練習工具", 4.4),
    ("BandLab SongStarter", "https://www.bandlab.com", "音樂", "AI 歌曲創意起點，生成旋律與和弦。", ["旋律", "和弦", "創作"], ["bandlab", "songstarter", "melody"], "免費", "歌曲創意靈感", 4.2),
    ("Orb Producer Suite", "https://www.orbplugins.com", "音樂", "AI 協助 MIDI 生成，輔助電子音樂製作。", ["MIDI", "電子", "DAW"], ["orb", "midi", "producer"], "付費", "AI 輔助 MIDI 創作", 4.1),
    ("WavTool", "https://wavtool.com", "音樂", "瀏覽器 AI DAW，文字指令編輯音樂。", ["DAW", "瀏覽器", "Agent"], ["wavtool", "daw", "browser"], "Freemium", "瀏覽器 AI 音樂製作", 4.2),
    ("Producer.ai", "https://producer.ai", "音樂", "AI 音樂製作人，文字描述生成完整曲目。", ["製作", "描述", "曲目"], ["producer.ai", "music production", "generate"], "Freemium", "文字生成完整曲目", 4.1),
    ("Soundful", "https://soundful.com", "音樂", "AI 免版稅音樂生成，模板豐富。", ["免版稅", "模板", "BGM"], ["soundful", "royalty free", "templates"], "Freemium", "模板式 BGM 生成", 4.2),
    ("Hydra II", "https://rightsify.com/hydra", "音樂", "Rightsify AI 音樂生成，商用授權清晰。", ["商用", "授權", "BGM"], ["hydra", "rightsify", "commercial"], "Freemium", "商用授權 AI 音樂", 4.1),
    # --- 搜尋研究 ---
    ("Perplexity", "https://www.perplexity.ai", "搜尋研究", "AI 搜尋引擎，回答附引用來源，適合查資料。", ["搜尋", "引用", "研究"], ["perplexity", "search", "research"], "Freemium", "有來源的 AI 搜尋問答", 4.6),
    ("Google AI Mode", "https://www.google.com", "搜尋研究", "Google 搜尋 AI 模式，整合 Gemini 回答複雜問題。", ["Google", "搜尋", "Gemini"], ["google ai", "search", "gemini"], "Freemium", "Google 搜尋 AI 回答", 4.4),
    ("Consensus", "https://consensus.app", "搜尋研究", "AI 學術論文搜尋，從研究文献提取答案。", ["論文", "學術", "研究"], ["consensus", "papers", "academic"], "Freemium", "學術論文 AI 搜尋", 4.4),
    ("Elicit", "https://elicit.com", "搜尋研究", "AI 研究助手，自動整理文獻與提取重點。", ["文獻", "整理", "研究"], ["elicit", "literature", "research"], "Freemium", "文獻回顧與整理", 4.4),
    ("Semantic Scholar", "https://www.semanticscholar.org", "搜尋研究", "AI 驅動學術搜尋，論文推薦與摘要。", ["學術", "論文", "AI"], ["semantic scholar", "papers", "ai"], "免費", "學術論文 AI 搜尋", 4.3),
    ("Scite.ai", "https://scite.ai", "搜尋研究", "AI 引用分析，判斷論文被支持或反駁。", ["引用", "分析", "論文"], ["scite", "citations", "research"], "Freemium", "論文引用脈絡分析", 4.3),
    ("Research Rabbit", "https://www.researchrabbit.ai", "搜尋研究", "AI 論文推薦與視覺化文獻網絡。", ["推薦", "視覺化", "論文"], ["research rabbit", "papers", "network"], "免費", "論文推薦與探索", 4.3),
    ("Connected Papers", "https://www.connectedpapers.com", "搜尋研究", "論文關聯視覺化，探索研究前沿。", ["視覺化", "關聯", "論文"], ["connected papers", "graph", "research"], "Freemium", "論文關聯圖探索", 4.2),
    ("Litmaps", "https://www.litmaps.com", "搜尋研究", "AI 文獻地圖，追蹤研究發展脈絡。", ["地圖", "文獻", "追蹤"], ["litmaps", "literature map", "research"], "Freemium", "文獻脈絡地圖", 4.2),
    ("NotebookLM", "https://notebooklm.google.com", "搜尋研究", "Google AI 筆記研究助手，上傳來源後問答。", ["Google", "筆記", "來源"], ["notebooklm", "google", "research"], "Freemium", "多來源 AI 研究筆記", 4.5),
    ("Glean", "https://www.glean.com", "搜尋研究", "企業 AI 知識搜尋，整合內部文件與 Slack。", ["企業", "知識", "搜尋"], ["glean", "enterprise search", "knowledge"], "付費", "企業內部知識搜尋", 4.4),
    ("Kagi", "https://kagi.com", "搜尋研究", "付費無廣告 AI 搜尋引擎，注重隱私。", ["隱私", "無廣告", "搜尋"], ["kagi", "search", "privacy"], "付費", "無廣告 AI 搜尋", 4.3),
    ("Brave Search", "https://search.brave.com", "搜尋研究", "Brave AI 搜尋摘要，獨立索引注重隱私。", ["Brave", "隱私", "摘要"], ["brave search", "ai summary", "privacy"], "Freemium", "隱私友善 AI 搜尋", 4.2),
    ("Andi Search", "https://andisearch.com", "搜尋研究", "對話式 AI 搜尋，直接回答而非連結列表。", ["對話", "搜尋", "回答"], ["andi", "conversational search"], "Freemium", "對話式 AI 搜尋", 4.1),
    ("Metaphor", "https://metaphor.systems", "搜尋研究", "AI 語意搜尋 API，理解意圖而非關鍵字。", ["語意", "API", "搜尋"], ["metaphor", "semantic search", "api"], "Freemium", "語意搜尋 API", 4.2),
    ("Exa", "https://exa.ai", "搜尋研究", "AI 原生搜尋 API，為 LLM 與 Agent 優化。", ["API", "Agent", "LLM"], ["exa", "search api", "llm"], "Freemium", "LLM 優化搜尋 API", 4.3),
    ("Tavily", "https://tavily.com", "搜尋研究", "AI Agent 搜尋 API，即時網路資訊檢索。", ["Agent", "API", "即時"], ["tavily", "agent search", "realtime"], "Freemium", "Agent 即時搜尋 API", 4.3),
    ("You.com Research", "https://you.com", "搜尋研究", "You.com 研究模式，深度搜尋與引用。", ["研究", "引用", "深度"], ["you.com research", "deep search"], "Freemium", "深度 AI 研究搜尋", 4.2),
    ("Bing Copilot Search", "https://www.bing.com/chat", "搜尋研究", "Bing AI 搜尋對話，微軟 GPT 整合。", ["Bing", "微軟", "GPT"], ["bing chat", "copilot search"], "Freemium", "微軟 AI 搜尋對話", 4.3),
    ("Wolfram Alpha", "https://www.wolframalpha.com", "搜尋研究", "計算知識引擎，數學與科學問題精準回答。", ["數學", "科學", "計算"], ["wolfram", "math", "computation"], "Freemium", "數學科學計算查詢", 4.4),
    ("Iris.ai", "https://iris.ai", "搜尋研究", "AI 研究項目助手，文獻映射與假設生成。", ["項目", "假設", "文獻"], ["iris.ai", "research project", "hypothesis"], "Freemium", "研究項目 AI 助手", 4.1),
    ("Scholarcy", "https://www.scholarcy.com", "搜尋研究", "AI 論文摘要，自動提取重點與參考。", ["摘要", "論文", "重點"], ["scholarcy", "paper summary", "flashcard"], "Freemium", "論文自動摘要", 4.2),
    ("Typeset", "https://typeset.io", "搜尋研究", "AI 學術寫作與論文搜尋平台 SciSpace。", ["SciSpace", "論文", "寫作"], ["scispace", "typeset", "academic writing"], "Freemium", "學術論文 AI 助手", 4.3),
    ("AlphaSense", "https://www.alpha-sense.com", "搜尋研究", "企業 AI 市場情報搜尋，金融與產業研究。", ["金融", "市場", "企業"], ["alphasense", "market intelligence", "finance"], "付費", "企業市場情報搜尋", 4.3),
    ("Feedly Leo", "https://feedly.com/leo", "搜尋研究", "AI 情報助理，自動整理 RSS 與產業新聞。", ["RSS", "情報", "新聞"], ["feedly leo", "news", "curation"], "Freemium", "AI 情報與新聞整理", 4.2),
    # --- 生產力 ---
    ("Notion AI", "https://www.notion.so/product/ai", "生產力", "Notion 內建 AI，摘要、改寫、整理知識庫。", ["Notion", "筆記", "摘要"], ["notion", "note", "knowledge"], "Freemium", "筆記與知識庫 AI 整理", 4.4),
    ("Gamma", "https://gamma.app", "生產力", "AI 簡報生成，輸入主題自動產出投影片。", ["簡報", "PPT", "投影片"], ["gamma", "ppt", "presentation"], "Freemium", "AI 一鍵生成簡報", 4.5),
    ("Motion", "https://www.usemotion.com", "生產力", "AI 排程助手，自動規劃任務與日曆。", ["排程", "日曆", "任務"], ["motion", "scheduling", "calendar"], "付費", "AI 自動排程", 4.3),
    ("Reclaim.ai", "https://reclaim.ai", "生產力", "AI 日曆優化，自動安排專注時間與會議。", ["日曆", "專注", "會議"], ["reclaim", "calendar", "focus time"], "Freemium", "日曆 AI 優化", 4.3),
    ("Clockwise", "https://www.getclockwise.com", "生產力", "AI 團隊日曆優化，減少會議碎片化。", ["團隊", "日曆", "會議"], ["clockwise", "team calendar", "meetings"], "Freemium", "團隊日曆優化", 4.2),
    ("Mem", "https://mem.ai", "生產力", "AI 筆記，自動連結相關想法與知識。", ["筆記", "連結", "知識"], ["mem", "notes", "knowledge graph"], "Freemium", "AI 智慧筆記", 4.2),
    ("Reflect", "https://reflect.app", "生產力", "AI 增強筆記，雙向連結加 GPT 助手。", ["筆記", "連結", "GPT"], ["reflect", "notes", "backlinks"], "Freemium", "AI 雙向連結筆記", 4.2),
    ("Taskade AI", "https://www.taskade.com", "生產力", "AI 協作工作空間，任務、文件、心智圖。", ["協作", "任務", "心智圖"], ["taskade", "collaboration", "mindmap"], "Freemium", "AI 協作工作空間", 4.2),
    ("ClickUp AI", "https://clickup.com/ai", "生產力", "ClickUp 內建 AI，任務摘要、寫作與搜尋。", ["專案", "任務", "PM"], ["clickup", "project management", "ai"], "Freemium", "專案管理 AI 助手", 4.3),
    ("Asana AI", "https://asana.com/product/ai", "生產力", "Asana AI 功能，智慧目標與工作流建議。", ["Asana", "專案", "工作流"], ["asana", "project", "workflow"], "Freemium", "團隊專案 AI 助手", 4.2),
    ("Monday AI", "https://monday.com/w/ai", "生產力", "Monday.com AI 助手，自動化工作流與摘要。", ["Monday", "自動化", "工作流"], ["monday", "automation", "workflow"], "Freemium", "工作流 AI 自動化", 4.2),
    ("Superhuman AI", "https://superhuman.com", "生產力", "AI 增強電子郵件，快速撰寫與整理收件匣。", ["Email", "收件匣", "快速"], ["superhuman", "email", "inbox"], "付費", "AI 增強 Email 效率", 4.4),
    ("Shortwave", "https://www.shortwave.com", "生產力", "AI 電子郵件客戶端，智慧搜尋與摘要。", ["Email", "搜尋", "摘要"], ["shortwave", "email", "ai search"], "Freemium", "AI Email 整理", 4.3),
    ("SaneBox", "https://www.sanebox.com", "生產力", "AI 郵件過濾，自動整理重要與次要郵件。", ["Email", "過濾", "整理"], ["sanebox", "email filter", "inbox"], "付費", "AI 郵件過濾整理", 4.3),
    ("Tactiq for Docs", "https://tactiq.io", "生產力", "會議摘要整合 Google Docs 與 Notion。", ["會議", "Docs", "整合"], ["tactiq docs", "meeting summary"], "Freemium", "會議摘要寫入文件", 4.2),
    ("Beautiful.ai", "https://www.beautiful.ai", "生產力", "AI 簡報設計，自動排版與視覺優化。", ["簡報", "排版", "設計"], ["beautiful.ai", "presentation", "design"], "Freemium", "AI 簡報排版", 4.3),
    ("Tome", "https://tome.app", "生產力", "AI 敘事簡報，生成故事化投影片與大綱。", ["敘事", "簡報", "故事"], ["tome", "storytelling", "presentation"], "Freemium", "故事化 AI 簡報", 4.2),
    ("SlidesAI", "https://www.slidesai.io", "生產力", "Google Slides AI 外掛，文字轉投影片。", ["Google Slides", "外掛", "PPT"], ["slidesai", "google slides", "ppt"], "Freemium", "Google Slides AI 外掛", 4.2),
    ("Magical", "https://www.getmagical.com", "生產力", "AI 文字擴展與表單自動填寫，跨網站生產力。", ["自動填寫", "擴展", "表單"], ["magical", "autofill", "text expander"], "Freemium", "跨網站文字自動化", 4.2),
    ("Text Blaze", "https://blaze.today", "生產力", "AI 文字片段與模板，快速回覆與自動化。", ["片段", "模板", "回覆"], ["text blaze", "snippets", "templates"], "Freemium", "文字片段自動化", 4.3),
    ("Zapier AI", "https://zapier.com/ai", "生產力", "AI 驅動自動化，自然語言建立 Zap 工作流。", ["自動化", "Zap", "工作流"], ["zapier", "automation", "workflow"], "Freemium", "自然語言建立自動化", 4.4),
    ("Make AI", "https://www.make.com", "生產力", "視覺化 AI 自動化平台（原 Integromat）。", ["自動化", "整合", "視覺化"], ["make", "integromat", "automation"], "Freemium", "視覺化 AI 自動化", 4.3),
    ("Bardeen", "https://www.bardeen.ai", "生產力", "AI 瀏覽器自動化，一鍵擷取資料與工作流。", ["瀏覽器", "自動化", "擷取"], ["bardeen", "browser automation", "scrape"], "Freemium", "瀏覽器 AI 自動化", 4.2),
    ("Raycast AI", "https://www.raycast.com/ai", "生產力", "Mac 啟動器 AI 助手，快速指令與 ChatGPT。", ["Mac", "啟動器", "快捷"], ["raycast", "launcher", "mac"], "Freemium", "Mac AI 啟動器", 4.4),
    ("Arc Max", "https://arc.net", "生產力", "Arc 瀏覽器 AI 功能，摘要、提問與整理分頁。", ["瀏覽器", "摘要", "分頁"], ["arc max", "browser", "ai"], "Freemium", "AI 瀏覽器助手", 4.3),
    # --- 翻譯 ---
    ("DeepL", "https://www.deepl.com", "翻譯", "高準確度 AI 翻譯，多語言品質業界領先。", ["翻譯", "多語言", "準確"], ["deepl", "translate", "language"], "Freemium", "高品質文件翻譯", 4.8),
    ("Google Translate", "https://translate.google.com", "翻譯", "Google AI 翻譯，支援 100+ 語言與相機翻譯。", ["Google", "多語言", "相機"], ["google translate", "multilingual"], "免費", "通用多語言翻譯", 4.3),
    ("Microsoft Translator", "https://www.microsoft.com/translator", "翻譯", "微軟 AI 翻譯，整合 Office 與 Teams。", ["微軟", "Office", "Teams"], ["microsoft translator", "office"], "免費", "微軟生態翻譯", 4.2),
    ("Reverso", "https://www.reverso.net", "翻譯", "AI 翻譯加例句與語境，語言學習常用。", ["例句", "語境", "學習"], ["reverso", "context", "examples"], "Freemium", "語境式翻譯學習", 4.3),
    ("Linguee", "https://www.linguee.com", "翻譯", "DeepL 旗下雙語例句搜尋與翻譯。", ["例句", "DeepL", "雙語"], ["linguee", "bilingual", "examples"], "Freemium", "雙語例句翻譯", 4.2),
    ("ModernMT", "https://www.modernmt.com", "翻譯", "自適應 AI 機器翻譯，企業本地化。", ["企業", "本地化", "自適應"], ["modernmt", "enterprise", "localization"], "Freemium", "企業自適應翻譯", 4.2),
    ("Smartling", "https://www.smartling.com", "翻譯", "AI 本地化平台，企業多語言內容管理。", ["本地化", "企業", "CMS"], ["smartling", "localization", "enterprise"], "付費", "企業本地化平台", 4.3),
    ("Unbabel", "https://unbabel.com", "翻譯", "AI 加人工審校翻譯，客服場景常用。", ["客服", "人工", "品質"], ["unbabel", "customer service", "hybrid"], "付費", "客服 AI 翻譯", 4.2),
    ("Phrase", "https://phrase.com", "翻譯", "AI TMS 翻譯管理系統，軟體本地化。", ["TMS", "軟體", "本地化"], ["phrase", "tms", "software localization"], "付費", "翻譯管理系統", 4.3),
    ("Lokalise AI", "https://lokalise.com", "翻譯", "AI 協作本地化平台，App 與網站多語言。", ["App", "協作", "本地化"], ["lokalise", "app localization", "collaboration"], "Freemium", "App 本地化協作", 4.3),
    ("Crowdin AI", "https://crowdin.com", "翻譯", "AI 輔助翻譯管理，開源與軟體專案常用。", ["開源", "協作", "TMS"], ["crowdin", "open source", "translation"], "Freemium", "開源專案本地化", 4.2),
    ("Mate Translate", "https://gikken.co/mate-translate", "翻譯", "Mac 選取即翻 AI 翻譯工具。", ["Mac", "選取", "即時"], ["mate translate", "mac", "instant"], "Freemium", "Mac 即時翻譯", 4.2),
    ("iTranslate", "https://itranslate.com", "翻譯", "AI 翻譯 App，離線與對話模式。", ["App", "離線", "對話"], ["itranslate", "mobile", "offline"], "Freemium", "手機 AI 翻譯", 4.1),
    ("Papago", "https://papago.naver.com", "翻譯", "Naver AI 翻譯，韓語與亞洲語言強。", ["Naver", "韓語", "亞洲"], ["papago", "naver", "korean"], "免費", "韓語亞洲語言翻譯", 4.3),
    ("有道翻譯", "https://fanyi.youdao.com", "翻譯", "網易有道 AI 翻譯，中英文與學術場景。", ["網易", "中文", "學術"], ["youdao", "有道", "chinese"], "Freemium", "中英文翻譯學習", 4.3),
    ("騰訊翻譯君", "https://fanyi.qq.com", "翻譯", "騰訊 AI 翻譯，多語言與 OCR 整合。", ["騰訊", "OCR", "中文"], ["tencent translate", "qq", "ocr"], "免費", "騰訊生態翻譯", 4.2),
    ("百度翻譯", "https://fanyi.baidu.com", "翻譯", "百度 AI 翻譯，文件與圖片翻譯。", ["百度", "文件", "圖片"], ["baidu translate", "document", "image"], "Freemium", "中文文件圖片翻譯", 4.2),
    ("Transifex AI", "https://www.transifex.com", "翻譯", "AI 本地化工作流，DevOps 整合。", ["DevOps", "工作流", "本地化"], ["transifex", "devops", "localization"], "Freemium", "DevOps 本地化", 4.2),
    ("Wordly", "https://wordly.ai", "翻譯", "AI 即時口譯，會議與活動多語言。", ["口譯", "即時", "會議"], ["wordly", "interpretation", "live"], "付費", "即時 AI 口譯", 4.3),
    ("KUDO AI", "https://kudo.ai", "翻譯", "AI 會議同聲傳譯平台。", ["同傳", "會議", "多語言"], ["kudo", "simultaneous", "interpretation"], "Freemium", "會議同聲傳譯", 4.2),
    ("Rask AI", "https://rask.ai", "翻譯", "AI 影片配音翻譯，口型同步多語言。", ["影片", "配音", "口型"], ["rask", "video dubbing", "lip sync"], "Freemium", "影片 AI 配音翻譯", 4.4),
    ("HeyGen Translate", "https://www.heygen.com/translate", "翻譯", "AI 影片翻譯，保留原講者聲音與口型。", ["影片", "翻譯", "Avatar"], ["heygen translate", "video translation"], "Freemium", "影片保留原聲翻譯", 4.4),
    ("BlipCut", "https://blipcut.com", "翻譯", "AI 影片翻譯與字幕生成。", ["影片", "字幕", "翻譯"], ["blipcut", "video subtitle", "translate"], "Freemium", "影片字幕 AI 翻譯", 4.2),
    ("Maestra", "https://maestra.ai", "翻譯", "AI 字幕、轉錄與翻譯一站式。", ["字幕", "轉錄", "翻譯"], ["maestra", "subtitle", "transcription"], "Freemium", "字幕轉錄翻譯", 4.2),
    ("Tarjimly", "https://tarjimly.org", "翻譯", "AI 輔助難民與移民翻譯（公益向）。", ["公益", "移民", "即時"], ["tarjimly", "nonprofit", "refugee"], "免費", "公益即時翻譯", 4.0),
    # --- 寫作 ---
    ("Grammarly", "https://www.grammarly.com", "寫作", "AI 英文寫作助手，文法潤飾與語氣調整。", ["英文", "文法", "潤飾"], ["grammarly", "english", "writing"], "Freemium", "英文寫作文法潤飾", 4.5),
    ("Jasper", "https://www.jasper.ai", "寫作", "行銷導向 AI 寫作，品牌文案與廣告內容。", ["行銷", "文案", "品牌"], ["jasper", "marketing", "copywriting"], "付費", "行銷文案與品牌內容", 4.3),
    ("Copy.ai", "https://www.copy.ai", "寫作", "AI 文案生成，社群貼文、Email、廣告。", ["文案", "社群", "Email"], ["copy.ai", "copywriting", "social"], "Freemium", "快速 AI 文案生成", 4.3),
    ("Writesonic", "https://writesonic.com", "寫作", "AI 寫作平台，SEO 文章與行銷內容。", ["SEO", "文章", "行銷"], ["writesonic", "seo", "blog"], "Freemium", "SEO 文章 AI 寫作", 4.3),
    ("Rytr", "https://rytr.me", "寫作", "平價 AI 寫作助手，多種語調與模板。", ["平價", "模板", "語調"], ["rytr", "affordable", "templates"], "Freemium", "平價 AI 寫作", 4.2),
    ("Anyword", "https://anyword.com", "寫作", "AI 行銷文案，預測轉換率的分數。", ["行銷", "轉換", "預測"], ["anyword", "conversion", "marketing"], "Freemium", "預測型行銷文案", 4.2),
    ("Wordtune", "https://www.wordtune.com", "寫作", "AI 改寫與潤色，調整語氣與清晰度。", ["改寫", "潤色", "語氣"], ["wordtune", "rewrite", "tone"], "Freemium", "句子改寫潤色", 4.3),
    ("QuillBot", "https://quillbot.com", "寫作", "AI 改寫、摘要、文法檢查與引用。", ["改寫", "摘要", "引用"], ["quillbot", "paraphrase", "summarize"], "Freemium", "改寫摘要文法檢查", 4.4),
    ("ProWritingAid", "https://prowritingaid.com", "寫作", "AI 寫作品質分析，深度文法與風格建議。", ["分析", "風格", "文法"], ["prowritingaid", "style", "grammar"], "Freemium", "深度寫作品質分析", 4.3),
    ("Hemingway Editor", "https://hemingwayapp.com", "寫作", "AI 可讀性分析，簡化複雜句子。", ["可讀性", "簡化", "英文"], ["hemingway", "readability", "clarity"], "Freemium", "英文可讀性優化", 4.2),
    ("Sudowrite", "https://www.sudowrite.com", "寫作", "AI 小說與創意寫作助手，情節與描寫。", ["小說", "創意", "情節"], ["sudowrite", "fiction", "creative writing"], "Freemium", "小說創意寫作", 4.4),
    ("NovelAI", "https://novelai.net", "寫作", "AI 故事與小說生成，可自訂風格。", ["小說", "故事", "角色"], ["novelai", "story", "fiction"], "Freemium", "AI 故事小說生成", 4.2),
    ("Squibler", "https://www.squibler.io", "寫作", "AI 書籍與劇本寫作平台。", ["書籍", "劇本", "大綱"], ["squibler", "book", "screenplay"], "Freemium", "書籍劇本 AI 寫作", 4.1),
    ("HyperWrite", "https://www.hyperwriteai.com", "寫作", "AI 寫作助手，瀏覽器擴充即時建議。", ["瀏覽器", "即時", "建議"], ["hyperwrite", "browser", "suggestions"], "Freemium", "瀏覽器即時寫作建議", 4.2),
    ("Lex", "https://lex.page", "寫作", "AI 寫作編輯器，專為長文與部落格。", ["編輯器", "部落格", "長文"], ["lex", "editor", "blog"], "Freemium", "AI 長文編輯器", 4.2),
    ("Notion AI Writer", "https://www.notion.so/product/ai", "寫作", "Notion 內 AI 寫作、摘要與翻譯。", ["Notion", "摘要", "寫作"], ["notion writer", "draft", "summarize"], "Freemium", "Notion 內 AI 寫作", 4.4),
    ("Writer.com", "https://writer.com", "寫作", "企業 AI 寫作平台，品牌語調一致性。", ["企業", "品牌", "語調"], ["writer.com", "enterprise", "brand voice"], "付費", "企業品牌語調寫作", 4.3),
    ("LongShot AI", "https://www.longshot.ai", "寫作", "AI 長文 SEO 內容生成與事實查核。", ["SEO", "長文", "查核"], ["longshot", "seo content", "fact check"], "Freemium", "SEO 長文內容", 4.2),
    ("Frase", "https://www.frase.io", "寫作", "AI SEO 內容研究與撰寫，SERP 分析。", ["SEO", "SERP", "研究"], ["frase", "seo research", "content"], "Freemium", "SEO 內容研究撰寫", 4.3),
    ("Surfer SEO", "https://surferseo.com", "寫作", "AI SEO 內容優化，關鍵字與結構建議。", ["SEO", "關鍵字", "優化"], ["surfer seo", "content optimization"], "Freemium", "SEO 內容優化", 4.4),
    ("KoalaWriter", "https://koala.sh", "寫作", "AI SEO 部落格文章一鍵生成。", ["SEO", "部落格", "文章"], ["koala writer", "blog", "seo"], "Freemium", "SEO 部落格生成", 4.2),
    ("Jenni AI", "https://jenni.ai", "寫作", "AI 學術寫作助手，引用與段落生成。", ["學術", "引用", "論文"], ["jenni", "academic writing", "citations"], "Freemium", "學術寫作 AI 助手", 4.3),
    ("Paperpal", "https://paperpal.com", "寫作", "AI 學術英文潤稿，期刊投稿常用。", ["學術", "潤稿", "期刊"], ["paperpal", "academic edit", "journal"], "Freemium", "學術英文 AI 潤稿", 4.3),
    ("Writefull", "https://writefull.com", "寫作", "AI 學術寫作回饋，整合 Overleaf。", ["學術", "Overleaf", "回饋"], ["writefull", "overleaf", "academic"], "Freemium", "Overleaf 學術寫作", 4.2),
    ("LanguageTool", "https://languagetool.org", "寫作", "多語言 AI 文法與拼字檢查。", ["多語言", "文法", "拼字"], ["languagetool", "grammar", "multilingual"], "Freemium", "多語言文法檢查", 4.3),
    # --- 圖像編輯 ---
    ("remove.bg", "https://www.remove.bg", "圖像編輯", "一鍵 AI 去背，上傳圖片自動移除背景。", ["去背", "摳圖", "背景"], ["remove.bg", "background removal"], "Freemium", "快速圖片去背", 4.6),
    ("Photoroom", "https://www.photoroom.com", "圖像編輯", "AI 產品攝影與去背，電商圖片常用。", ["電商", "產品", "去背"], ["photoroom", "product photo", "ecommerce"], "Freemium", "電商產品 AI 攝影", 4.5),
    ("Clipdrop", "https://clipdrop.co", "圖像編輯", "AI 圖像編輯套件，去背、放大、重打光。", ["套件", "去背", "重打光"], ["clipdrop", "cleanup", "relight"], "Freemium", "多合一 AI 圖像編輯", 4.4),
    ("Cleanup.pictures", "https://cleanup.pictures", "圖像編輯", "AI 移除圖片中不需要的物件。", ["移除", "修復", "物件"], ["cleanup pictures", "object removal"], "Freemium", "移除圖中多餘物件", 4.4),
    ("Magic Eraser", "https://magicstudio.com/magiceraser", "圖像編輯", "AI 魔術橡皮擦，一鍵移除圖中元素。", ["橡皮擦", "移除", "修復"], ["magic eraser", "remove object"], "Freemium", "魔術橡皮擦修圖", 4.3),
    ("Adobe Photoshop AI", "https://www.adobe.com/products/photoshop.html", "圖像編輯", "Photoshop 生成式填充與 AI 修圖功能。", ["Photoshop", "Adobe", "生成式"], ["photoshop ai", "generative fill", "adobe"], "付費", "專業 AI 修圖", 4.6),
    ("Luminar Neo", "https://skylum.com/luminar", "圖像編輯", "AI 照片編輯，天空替換與人像增強。", ["照片", "天空", "人像"], ["luminar neo", "photo edit", "sky"], "付費", "AI 照片後製", 4.4),
    ("Topaz Photo AI", "https://www.topazlabs.com/topaz-photo-ai", "圖像編輯", "AI 降噪、銳化與放大，攝影後製。", ["降噪", "銳化", "放大"], ["topaz photo", "denoise", "upscale"], "付費", "攝影 AI 後製", 4.5),
    ("Let's Enhance", "https://letsenhance.io", "圖像編輯", "AI 圖片放大至 4K+，提升細節。", ["放大", "4K", "細節"], ["lets enhance", "upscale", "resolution"], "Freemium", "AI 圖片放大", 4.3),
    ("Upscale.media", "https://www.upscale.media", "圖像編輯", "免費 AI 圖片放大與增強。", ["放大", "免費", "增強"], ["upscale media", "free upscale"], "Freemium", "免費圖片放大", 4.2),
    ("Pixelcut", "https://www.pixelcut.ai", "圖像編輯", "AI 產品圖與背景生成，電商與社群。", ["產品", "背景", "電商"], ["pixelcut", "product", "background"], "Freemium", "產品圖 AI 編輯", 4.3),
    ("Fotor AI", "https://www.fotor.com", "圖像編輯", "AI 照片編輯與設計，一鍵美化。", ["照片", "美化", "設計"], ["fotor", "photo edit", "enhance"], "Freemium", "一鍵 AI 照片美化", 4.2),
    ("BeFunky", "https://www.befunky.com", "圖像編輯", "AI 照片編輯與拼貼，入門友善。", ["拼貼", "入門", "照片"], ["befunky", "collage", "photo"], "Freemium", "入門 AI 照片編輯", 4.1),
    ("Pixlr AI", "https://pixlr.com", "圖像編輯", "線上 AI 圖像編輯，生成式填充與去背。", ["線上", "生成式", "去背"], ["pixlr", "online edit", "generative"], "Freemium", "線上 AI 修圖", 4.2),
    ("Canva Magic Edit", "https://www.canva.com", "圖像編輯", "Canva AI 魔術編輯，選取區域替換內容。", ["Canva", "魔術", "替換"], ["canva magic edit", "inpaint"], "Freemium", "Canva AI 魔術編輯", 4.4),
    ("Adobe Lightroom AI", "https://www.adobe.com/products/photoshop-lightroom.html", "圖像編輯", "Lightroom AI 降噪與自動調色。", ["Lightroom", "降噪", "調色"], ["lightroom ai", "denoise", "color"], "付費", "AI 批量照片調色", 4.5),
    ("Remini", "https://remini.ai", "圖像編輯", "AI 老照片修復與畫質增強 App。", ["修復", "老照片", "App"], ["remini", "photo restore", "enhance"], "Freemium", "老照片 AI 修復", 4.3),
    ("VanceAI", "https://vanceai.com", "圖像編輯", "AI 圖片增強、去背、卡通化等工具集。", ["工具集", "卡通", "增強"], ["vanceai", "cartoon", "enhance"], "Freemium", "多種 AI 圖像工具", 4.2),
    ("BgEraser", "https://bgeraser.com", "圖像編輯", "AI 去背與背景移除，批量處理。", ["去背", "批量", "背景"], ["bgeraser", "batch", "background"], "Freemium", "批量 AI 去背", 4.2),
    ("Slazzer", "https://www.slazzer.com", "圖像編輯", "AI 自動去背 API 與線上工具。", ["API", "去背", "自動"], ["slazzer", "background removal", "api"], "Freemium", "去背 API 與工具", 4.2),
    ("Palette.fm", "https://palette.fm", "圖像編輯", "AI 黑白照片上色，歷史照片修復。", ["上色", "黑白", "修復"], ["palette.fm", "colorize", "restore"], "Freemium", "黑白照片 AI 上色", 4.3),
    ("Hotpot.ai", "https://hotpot.ai", "圖像編輯", "AI 圖像工具集，頭像、去背、修復。", ["工具集", "頭像", "修復"], ["hotpot", "avatar", "tools"], "Freemium", "多種 AI 圖像小工具", 4.2),
    ("Aragon AI", "https://www.aragon.ai", "圖像編輯", "AI 專業頭像生成，LinkedIn 常用。", ["頭像", "LinkedIn", "專業"], ["aragon", "headshot", "professional"], "Freemium", "AI 專業頭像", 4.3),
    ("ProfilePicture.ai", "https://www.profilepicture.ai", "圖像編輯", "AI 社群頭像生成，多種風格。", ["頭像", "社群", "風格"], ["profilepicture", "avatar", "social"], "Freemium", "AI 社群頭像", 4.2),
    ("Headshot Pro", "https://www.headshotpro.com", "圖像編輯", "AI 商業證件照生成，無需攝影棚。", ["證件照", "商業", "頭像"], ["headshot pro", "business photo"], "Freemium", "AI 商業證件照", 4.3),
    ("Cutout.pro", "https://www.cutout.pro", "圖像編輯", "AI 去背、修復與證件照工具集。", ["去背", "修復", "工具集"], ["cutout pro", "background", "tools"], "Freemium", "多合一 AI 修圖工具", 4.2),
    ("Icons8 Background Remover", "https://icons8.com/bgremover", "圖像編輯", "Icons8 AI 去背與背景替換工具。", ["Icons8", "去背", "替換"], ["icons8", "bg remover", "background"], "Freemium", "快速去背替換背景", 4.2),
    ("Adobe Firefly Image", "https://firefly.adobe.com/generate/images", "圖像生成", "Adobe Firefly 官方 AI 圖像生成頁面。", ["Adobe", "Firefly", "商用"], ["firefly image", "adobe generate"], "Freemium", "Adobe 官方 AI 繪圖", 4.5),
    ("ComfyUI", "https://github.com/comfyanonymous/ComfyUI", "圖像生成", "節點式 Stable Diffusion 工作流 UI，高度可定制。", ["SD", "節點", "開源"], ["comfyui", "workflow", "stable diffusion"], "免費", "進階 SD 工作流", 4.5),
    ("Civitai", "https://civitai.com", "圖像生成", "Stable Diffusion 模型與作品社群平台。", ["SD", "模型", "社群"], ["civitai", "models", "lora"], "Freemium", "SD 模型下載社群", 4.4),
    ("FlowGPT", "https://flowgpt.com", "對話助手", "AI 提示詞與 Chatbot 模板分享社群。", ["提示詞", "模板", "社群"], ["flowgpt", "prompts", "chatbot"], "Freemium", "提示詞模板社群", 4.2),
    ("PromptBase", "https://promptbase.com", "圖像生成", "Midjourney 與 SD 提示詞交易市集。", ["提示詞", "Midjourney", "市集"], ["promptbase", "prompt market", "mj"], "Freemium", "購買優質提示詞", 4.1),
]


def slugify(name: str, keywords=None) -> str:
    s = unicodedata.normalize("NFKD", name)
    s = s.encode("ascii", "ignore").decode("ascii")
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower()
    if not s and keywords:
        s = re.sub(r"[^a-zA-Z0-9]+", "-", keywords[0]).strip("-").lower()
    return s or "tool"


def build_tools():
    seen_ids = set()
    seen_urls = set()
    tools = []
    for row in SEEDS:
        name, url, category, desc, tags, keywords, pricing, best_for, rating = row
        base_id = KNOWN_IDS.get(name, slugify(name, keywords))
        tool_id = base_id
        n = 2
        while tool_id in seen_ids:
            tool_id = f"{base_id}-{n}"
            n += 1
        seen_ids.add(tool_id)
        if url in seen_urls:
            continue
        seen_urls.add(url)
        tools.append(
            {
                "id": tool_id,
                "name": name,
                "description": desc,
                "category": category,
                "tags": tags,
                "keywords": keywords,
                "rating": rating,
                "pricing": pricing,
                "url": url,
                "bestFor": best_for,
            }
        )
    return tools


def main():
    tools = build_tools()
    if len(tools) < TARGET:
        raise SystemExit(f"Only {len(tools)} unique tools; need {TARGET}")
    if len(tools) > TARGET:
        tools = tools[:TARGET]
    OUT.write_text(json.dumps(tools, ensure_ascii=False, indent=2), encoding="utf-8")
    cats = {}
    for t in tools:
        cats[t["category"]] = cats.get(t["category"], 0) + 1
    print(f"Wrote {len(tools)} tools to {OUT}")
    for cat, count in sorted(cats.items()):
        print(f"  {cat}: {count}")


if __name__ == "__main__":
    main()
