const AI_TOOLS = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    description: "OpenAI 出品的通用對話 AI，擅長寫作、問答、腦力激盪與日常任務。",
    category: "對話助手",
    tags: ["聊天", "寫作", "問答", "GPT", "OpenAI"],
    keywords: ["chat", "gpt", "openai", "寫文章", "文案", "通用"],
    rating: 4.8,
    pricing: "Freemium",
    url: "https://chat.openai.com",
    bestFor: "日常問答與文案撰寫",
  },
  {
    id: "claude",
    name: "Claude",
    description: "Anthropic 開發的 AI 助手，長文理解與程式碼分析表現優異，回答風格細緻。",
    category: "對話助手",
    tags: ["聊天", "長文", "分析", "Anthropic"],
    keywords: ["claude", "anthropic", "分析", "程式", "coding"],
    rating: 4.7,
    pricing: "Freemium",
    url: "https://claude.ai",
    bestFor: "長文件分析與深度推理",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    description: "Google 的多模態 AI，整合搜尋與 Google 生態，適合研究與資訊整理。",
    category: "對話助手",
    tags: ["Google", "搜尋", "多模態", "研究"],
    keywords: ["gemini", "google", "搜尋", "research", "研究"],
    rating: 4.5,
    pricing: "Freemium",
    url: "https://gemini.google.com",
    bestFor: "結合搜尋的研究與整理",
  },
  {
    id: "cursor",
    name: "Cursor",
    description: "AI 驅動的程式編輯器，可自動讀取、修改程式碼並執行終端指令。",
    category: "程式開發",
    tags: ["IDE", "編程", "Agent", "VS Code"],
    keywords: ["cursor", "coding", "程式", "開發", "agent", "寫code"],
    rating: 4.8,
    pricing: "Freemium",
    url: "https://cursor.com",
    bestFor: "AI 輔助寫程式與除錯",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description: "微軟出品的 AI 程式助手，在編輯器內即時補全程式碼與建議。",
    category: "程式開發",
    tags: ["GitHub", "補全", "IDE", "微軟"],
    keywords: ["copilot", "github", "程式", "coding", "autocomplete"],
    rating: 4.6,
    pricing: "付費",
    url: "https://github.com/features/copilot",
    bestFor: "編輯器內程式碼自動補全",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    description: "高品質 AI 繪圖工具，藝術風格強、視覺效果出色，適合創意設計。",
    category: "圖像生成",
    tags: ["繪圖", "設計", "藝術", "Discord"],
    keywords: ["midjourney", "mj", "繪圖", "image", "圖片", "design", "設計"],
    rating: 4.7,
    pricing: "付費",
    url: "https://www.midjourney.com",
    bestFor: "高質感藝術風格圖像",
  },
  {
    id: "dalle",
    name: "DALL·E",
    description: "OpenAI 的 AI 繪圖工具，文字描述即可生成圖片，與 ChatGPT 整合。",
    category: "圖像生成",
    tags: ["OpenAI", "繪圖", "ChatGPT"],
    keywords: ["dalle", "dall-e", "繪圖", "圖片", "openai", "image"],
    rating: 4.4,
    pricing: "Freemium",
    url: "https://openai.com/dall-e",
    bestFor: "快速文字轉圖片",
  },
  {
    id: "canva-ai",
    name: "Canva AI",
    description: "Canva 內建 AI 功能，一鍵生成海報、簡報、社群貼文等設計素材。",
    category: "設計",
    tags: ["Canva", "海報", "簡報", "社群"],
    keywords: ["canva", "設計", "海報", "ppt", "簡報", "社群", "marketing"],
    rating: 4.5,
    pricing: "Freemium",
    url: "https://www.canva.com",
    bestFor: "非設計師快速做視覺素材",
  },
  {
    id: "runway",
    name: "Runway",
    description: "專業 AI 影片生成與編輯平台，支援文字轉影片、去背、特效等。",
    category: "影片",
    tags: ["影片", "Video", "剪輯", "Gen-3"],
    keywords: ["runway", "video", "影片", "短片", "剪輯", "動畫"],
    rating: 4.6,
    pricing: "Freemium",
    url: "https://runwayml.com",
    bestFor: "AI 影片生成與剪輯",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    description: "頂尖 AI 語音合成工具，可生成自然的人聲配音與多語言朗讀。",
    category: "語音",
    tags: ["配音", "TTS", "語音", "有聲書"],
    keywords: ["elevenlabs", "語音", "voice", "配音", "tts", "朗讀", "有聲"],
    rating: 4.7,
    pricing: "Freemium",
    url: "https://elevenlabs.io",
    bestFor: "自然語音合成與配音",
  },
  {
    id: "suno",
    name: "Suno",
    description: "AI 音樂生成工具，輸入描述即可創作完整歌曲含人聲。",
    category: "音樂",
    tags: ["音樂", "作曲", "歌曲", "BGM"],
    keywords: ["suno", "music", "音樂", "作曲", "歌曲", "bgm"],
    rating: 4.5,
    pricing: "Freemium",
    url: "https://suno.com",
    bestFor: "快速生成 AI 音樂",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    description: "AI 搜尋引擎，回答附引用來源，適合查資料、研究與事實查核。",
    category: "搜尋研究",
    tags: ["搜尋", "研究", "引用", "查資料"],
    keywords: ["perplexity", "搜尋", "search", "研究", "查詢", "research"],
    rating: 4.6,
    pricing: "Freemium",
    url: "https://www.perplexity.ai",
    bestFor: "有來源的 AI 搜尋問答",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    description: "整合在 Notion 筆記中的 AI，協助摘要、改寫、整理知識庫。",
    category: "生產力",
    tags: ["Notion", "筆記", "摘要", "知識管理"],
    keywords: ["notion", "筆記", "note", "摘要", "整理", "生產力"],
    rating: 4.4,
    pricing: "Freemium",
    url: "https://www.notion.so/product/ai",
    bestFor: "筆記與知識庫 AI 整理",
  },
  {
    id: "deepl",
    name: "DeepL",
    description: "高準確度 AI 翻譯工具，多語言翻譯品質業界領先。",
    category: "翻譯",
    tags: ["翻譯", "多語言", "Localization"],
    keywords: ["deepl", "translate", "翻譯", "英文", "中文", "language"],
    rating: 4.8,
    pricing: "Freemium",
    url: "https://www.deepl.com",
    bestFor: "高品質文件翻譯",
  },
  {
    id: "grammarly",
    name: "Grammarly",
    description: "AI 英文寫作助手，檢查文法、潤飾語氣、提升寫作品質。",
    category: "寫作",
    tags: ["英文", "文法", "潤飾", "Writing"],
    keywords: ["grammarly", "英文", "english", "文法", "寫作", "writing"],
    rating: 4.5,
    pricing: "Freemium",
    url: "https://www.grammarly.com",
    bestFor: "英文寫作文法潤飾",
  },
  {
    id: "figma-ai",
    name: "Figma AI",
    description: "Figma 內建 AI 設計助手，快速生成 UI 原型與設計建議。",
    category: "設計",
    tags: ["Figma", "UI", "UX", "原型"],
    keywords: ["figma", "ui", "ux", "設計", "prototype", "介面"],
    rating: 4.4,
    pricing: "Freemium",
    url: "https://www.figma.com",
    bestFor: "UI/UX 設計與原型",
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    description: "開源 AI 繪圖模型，可本地部署，高度客製化，社群資源豐富。",
    category: "圖像生成",
    tags: ["開源", "本地", "繪圖", "ComfyUI"],
    keywords: ["stable diffusion", "sd", "開源", "open source", "繪圖", "local"],
    rating: 4.3,
    pricing: "免費",
    url: "https://stability.ai",
    bestFor: "可自架的開源繪圖",
  },
  {
    id: "kimi",
    name: "Kimi",
    description: "月之暗面出品的 AI 助手，中文理解強，支援超長上下文。",
    category: "對話助手",
    tags: ["中文", "長上下文", "Moonshot"],
    keywords: ["kimi", "月之暗面", "中文", "chinese", "長文"],
    rating: 4.5,
    pricing: "Freemium",
    url: "https://kimi.moonshot.cn",
    bestFor: "中文長文理解與問答",
  },
  {
    id: "codeium",
    name: "Codeium",
    description: "免費 AI 程式碼助手，支援多種 IDE，提供補全與聊天功能。",
    category: "程式開發",
    tags: ["免費", "補全", "IDE", "Windsurf"],
    keywords: ["codeium", "windsurf", "free", "免費", "coding", "程式"],
    rating: 4.4,
    pricing: "免費",
    url: "https://codeium.com",
    bestFor: "免費程式碼 AI 補全",
  },
  {
    id: "gamma",
    name: "Gamma",
    description: "AI 簡報生成工具，輸入主題自動產出精美投影片。",
    category: "生產力",
    tags: ["簡報", "PPT", "投影片", "Presentation"],
    keywords: ["gamma", "ppt", "簡報", "presentation", "投影片", "slides"],
    rating: 4.5,
    pricing: "Freemium",
    url: "https://gamma.app",
    bestFor: "AI 一鍵生成簡報",
  },
  {
    id: "remove-bg",
    name: "remove.bg",
    description: "一鍵 AI 去背工具，上傳圖片自動移除背景，速度快又準確。",
    category: "圖像編輯",
    tags: ["去背", "摳圖", "背景移除", "Photo"],
    keywords: ["remove.bg", "去背", "background", "摳圖", "photo", "圖片"],
    rating: 4.6,
    pricing: "Freemium",
    url: "https://www.remove.bg",
    bestFor: "快速圖片去背",
  },
  {
    id: "otter",
    name: "Otter.ai",
    description: "AI 會議逐字稿工具，自動轉錄語音並生成摘要。",
    category: "語音",
    tags: ["會議", "逐字稿", "轉錄", "Transcription"],
    keywords: ["otter", "會議", "meeting", "逐字稿", "transcription", "錄音"],
    rating: 4.4,
    pricing: "Freemium",
    url: "https://otter.ai",
    bestFor: "會議語音轉文字",
  },
  {
    id: "jasper",
    name: "Jasper",
    description: "行銷導向 AI 寫作平台，專為品牌文案、廣告與社群內容設計。",
    category: "寫作",
    tags: ["行銷", "文案", "Marketing", "品牌"],
    keywords: ["jasper", "marketing", "行銷", "文案", "copywriting", "廣告"],
    rating: 4.3,
    pricing: "付費",
    url: "https://www.jasper.ai",
    bestFor: "行銷文案與品牌內容",
  },
  {
    id: "pika",
    name: "Pika",
    description: "易上手的 AI 影片生成工具，文字或圖片即可生成短影片。",
    category: "影片",
    tags: ["短片", "Video", "動畫", "社群"],
    keywords: ["pika", "video", "影片", "短片", "動畫", "tiktok"],
    rating: 4.4,
    pricing: "Freemium",
    url: "https://pika.art",
    bestFor: "輕量 AI 短影片製作",
  },
];
